---
title: "preliminary visualizations"
author: "An Bui"
date: "10/6/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 0. set up
```{r}
# source the cleaning/summarizing script, which sources the set up
source(here::here("code", "01_cleaning-and-summarizing.R"))
```

# 1. FvFm 

## a. box plot

```{r}
ggplot(fvfm_summary, aes(x = sp_code, y = mean)) +
  geom_boxplot() +
  geom_jitter() +
  facet_wrap(~ pigment_type, scales = "free_x") +
  scale_x_discrete(guide = guide_axis(n.dodge = 2)) +
  theme_bw()

# ggsave(here::here("figures/prelim-visualizations", "20211006_fvfm-boxplot.jpg"))
```

# 2. Thickness

## a. box plot

```{r}
ggplot(thickness_summary, aes(x = sp_code, y = mean)) +
  geom_boxplot() +
  geom_jitter() +
  facet_wrap(~ pigment_type, scales = "free_x") +
  scale_x_discrete(guide = guide_axis(n.dodge = 2)) +
  theme_bw()

# ggsave(here::here("figures/prelim-visualizations", "20211011_thickness-boxplot.jpg"))
```

# 3. Dry weight

## a. box plot

```{r}
ggplot(dryw_summary, aes(x = sp_code, y = weight_dry_mg)) +
  geom_boxplot() +
  geom_jitter() +
  facet_wrap(~ pigment_type, scales = "free_x") +
  scale_x_discrete(guide = guide_axis(n.dodge = 2)) +
  theme_bw()

# ggsave(here::here("figures/prelim-visualizations", "20211011_dryw-boxplot.jpg"))
```

As a note: something needs to happen to be able to filter out the things that are true thalli (e.g. thallus on PTCA) AND things that are whole individuals that are basically thalli (e.g. BF). Maybe code those in as "thallus" and go from there?

# 4. volume

## a. box plot
```{r}
ggplot(volume_summary, aes(x = sp_code, y = volume_total_mL)) +
  geom_boxplot() +
  geom_jitter() +
  facet_wrap(~ pigment_type, scales = "free_x") +
  scale_x_discrete(guide = guide_axis(n.dodge = 2)) +
  theme_bw()

# ggsave(here::here("figures/prelim-visualizations", "20211011_volume-boxplot.jpg"))
```




