---
title: "ordinations"
author: "An Bui"
date: "10/25/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# source the cleaning/summarizing script, which sources the set up
source(here::here("code", "01a_trait-cleaning.R"))
```

# 0. Orientation

Necessary data frames are `tbs_matrix` created in the set up script.     

# 1. trait PCoA

```{r}
gower_mat <- ind_traits %>% 
  filter(sp_code %in% algae_proposal) %>% 
  # filter(!(sp_code %in% c("CO"))) %>% 
  filter(!(specimen_ID %in% recruits)) %>% 
  # weird Nienburgia?
  filter(!(specimen_ID == "20210721-BULL-023")) %>% 
  # take out standard error
  dplyr::select(!ends_with("_se")) %>% 
  # take out irrelevant columns
  dplyr::select(-c(sp_code, scientific_name, life_habit, posture, branching_yn, lifestage, method, year)) %>% 
  # take out date selected and site
  dplyr::select(-c(date_collected, site)) %>% 
  column_to_rownames("specimen_ID") %>% 
  # convert categorical traits into factors
  mutate(growth_form = as_factor(growth_form),
         pigment_type = as_factor(pigment_type),
         longevity = as_factor(longevity))

# note: PCOA is based on distance matrices, so never actually sees "species"
# add species by calculating weighted averages: from original data matrix of traits by species, average abundance and axis scores for all sites
tbs_gower <- FD::gowdis(gower_mat)
tbs_pcoa <- cmdscale(tbs_gower, eig = TRUE)
ordiplot(tbs_pcoa, display = "sites", type = "text")

tbs_gower_daisy <- daisy(gower_mat, metric = "gower") # same as above
tbs_pcoa_daisy <- cmdscale(tbs_gower_daisy, eig = TRUE)
ordiplot(tbs_pcoa_daisy, display = "sites", type = "text")
biplot.pcoa(ape::pcoa(tbs_gower_daisy))
test_pcoa <- ape::pcoa(tbs_gower_daisy, correction = "lingoes") 
test_pcoa

# tbs_pcoa <- wcmdscale(tbs_gower, eig = TRUE)
# tbs_pcoa <- ape::pcoa(tbs_gower, correction = "none")
# biplot(ape::pcoa(tbs_gower, correction = "none"))
# ordiplot(scores(tbs_pcoa, choices=c(1,2)), type="none", main="PCoA with species weighted averages")
# tbs.wa <- wascores(tbs_pcoa$points[,1:2], tbs_matrix)
# text(tbs.wa, rownames(tbs.wa), cex=0.7, col="red")
# biplot.pcoa(tbs_gower, tbs_pcoa, dir.axis1 = -1)
# tbs_pcoa$species <- wascores(x = tbs_pcoa$points, , expand = TRUE)
p1 <- ordiplot(tbs_pcoa, display = "sites", type = "none")
points1 <- points(p1, "sites", pch = 21, col = "red", bg = "yellow")
text(p1, "sites", col = "blue", cex = 0.9)
# identify(p1, "sites")



pcoa_spp_scores <- scores(tbs_pcoa, display = "sites") %>% 
  as.data.frame() %>% 
  rownames_to_column("specimen_ID") %>% 
  left_join(., metadata_ind, by = "specimen_ID")

pcoa_trait_scores <- scores(tbs_pcoa, choices = c(1,2)) %>% 
  as.data.frame()
ggplot(pcoa_spp_scores, aes(x = Dim1, y = Dim2, color = sp_code, shape = site)) +
  geom_hline(yintercept = 0, color = "grey", lty = 3) +
  geom_vline(xintercept = 0, color = "grey", lty = 3) +
  geom_point(alpha = 0.8, size = 3) +
  theme_bw()
```

# 2. PCA

```{r}
# sp_int_matrix <- ind_traits %>% 
#   filter(sp_code %in% algae_proposal) %>% 
#   filter(!(sp_code %in% c("CO"))) %>% 
#   # weird Nienburgia?
#   filter(!(specimen_ID == "20210721-BULL-023"))

pca_mat <- ind_traits %>% 
  filter(sp_code %in% algae_proposal) %>% 
  # filter(!(sp_code %in% c("CO"))) %>% 
  # filter(!(sp_code == "PTCA" & lifestage == "recruit")) %>% 
  # weird Nienburgia?
  filter(!(specimen_ID %in% c("20210721-BULL-023", "20210719-IVEE-009"))) %>% 
  mutate(growth_form_num = case_when(
    growth_form == "leathery_macrophyte" ~ 1,
    growth_form == "corticated_macrophytes" ~ 2,
    growth_form == "corticated_foliose" ~ 3
  ), 
  pigment_type_num = case_when(
    pigment_type == "red" ~ 1,
    pigment_type == "brown" ~ 2
  ), 
  longevity_num = case_when(
    longevity == "annual" ~ 1,
    longevity == "perennial" ~ 3,
    longevity == "annual or perennial" ~ 2
  )) %>% 
  # taking out max height for now
  dplyr::select(specimen_ID, maximum_height, total_volume, total_dry, sta_mean, tdmc_mean, sav_mean, sap_mean, fvfm_mean, thickness_mm_mean) %>% 
  column_to_rownames("specimen_ID") %>% 
  drop_na()

# , growth_form_num, pigment_type_num, longevity_num 
# frond_length_mean, frond_width_mean
```


```{r}
# tbs matrix filtered for species in proposal
# doesn't include Nienburgia or Corallina
# sp_int_matrix <- tbs_matrix %>% 
#   filter(sp_code %in% algae_proposal) %>% 
#   filter(!(sp_code %in% c("CO", "Nandersoniana")))
# 
# filtered_matrix <- tbs_matrix %>% 
#   filter(!(sp_code %in% c("MAPY", "CO", "Nandersoniana")))

# matrix_choice <- pca_mat

# only include numeric variables
# tbs_pca <- rda(matrix_choice[, 2:10], scale = TRUE)
tbs_pca <- rda(pca_mat, scale = TRUE)

# extract proportion explained for each axis
summary(tbs_pca)
loadings <- scores(tbs_pca, display = 'species', scaling = 0)
sort(abs(loadings[,2]), decreasing = TRUE)
# tbs_pca$CA
# simple biplot (compare with ggplot output to make sure it's right)
biplot(tbs_pca)

# species points
PCAscores <- scores(tbs_pca, display = "sites", choices = c(1, 2)) %>% 
  as.data.frame() %>% 
  rownames_to_column("specimen_ID") %>% 
  left_join(metadata_ind, by = "specimen_ID") %>% 
  left_join(., coarse_traits, by = "sp_code") %>% 
  mutate(scientific_name = factor(scientific_name, levels = algae_proposal_sciname_factors))

PCAscores_13 <- scores(tbs_pca, display = "sites", choices = c(1, 3)) %>% 
  as.data.frame() %>% 
  rownames_to_column("specimen_ID") %>% 
  left_join(metadata_ind, by = "specimen_ID") %>% 
  left_join(., coarse_traits, by = "sp_code") %>% 
  mutate(scientific_name = factor(scientific_name, levels = algae_proposal_sciname_factors))

# trait vectors
PCAvect <- scores(tbs_pca, display = "species", choices = c(1, 2)) %>% 
  as.data.frame()

PCAvect_13 <- scores(tbs_pca, display = "species", choices = c(1, 3)) %>% 
  as.data.frame()

# plot PCA
plot_PCA_12 <- ggplot() +
  coord_cartesian() +
  geom_vline(xintercept = c(0), color = "grey70", linetype = 2) +
  geom_hline(yintercept = c(0), color = "grey70", linetype = 2) +
  geom_point(data = PCAscores, aes(x = PC1, y = PC2, color = scientific_name, shape = site), size = 4) +
  # geom_text(data = PCAscores, aes(x = PC1, y = PC2, color = scientific_name, label = specimen_ID)) +
  scale_color_manual(values = algae_colors) +
  geom_segment(data = PCAvect, aes(x = 0, y = 0, xend = PC1, yend = PC2), arrow = arrow(length = unit(0.2, "cm")), linewidth = 1) +
  geom_text(data = PCAvect, aes(x = PC1, y = PC2, label = rownames(PCAvect)), size = 5, alpha = 0.8) +
  # scale_x_continuous(limits = c(-1.75, 3.75)) +
  # scale_y_continuous(limits = c(-2, 3.25)) +
  theme_bw() +
  guides(colour = guide_legend(ncol = 1),
         shape = guide_legend(ncol = 1)) +
  theme(legend.position = "right", 
        # legend.box = "", 
        legend.margin = margin(),
        axis.title = element_text(size = 18),
        axis.text = element_text(size = 16),
        title = element_text(size = 20),
        legend.text = element_text(size = 12)) +
  labs(x = "PC1 (28.1%)",
       y = "PC2 (21.4%)",
       title = "PC1 and PC2",
       color = "Scientific name") 
plot_PCA_12

plot_PCA_13 <- ggplot() +
  coord_cartesian() +
  geom_vline(xintercept = c(0), color = "grey70", linetype = 2) +
  geom_hline(yintercept = c(0), color = "grey70", linetype = 2) +
  geom_point(data = PCAscores_13, aes(x = PC1, y = PC3, color = scientific_name, shape = site), size = 4) +
  # geom_text(data = PCAscores, aes(x = PC1, y = PC2, color = scientific_name, label = specimen_ID)) +
  scale_color_manual(values = algae_colors) +

  geom_segment(data = PCAvect_13, aes(x = 0, y = 0, xend = PC1, yend = PC3), arrow = arrow(length = unit(0.2, "cm")), linewidth = 1) +
  geom_text(data = PCAvect_13, aes(x = PC1, y = PC3, label = rownames(PCAvect)), size = 5, alpha = 0.8) +
  # scale_x_continuous(limits = c(-1.5, 2.3)) +
  # scale_y_continuous(limits = c(-3, 2)) +
  theme_bw() +
  guides(colour = guide_legend(ncol = 2),
         shape = guide_legend(ncol = 2)) +
  theme(legend.position = "bottom", 
        legend.box = "vertical", 
        legend.margin = margin(),
        axis.title = element_text(size = 18),
        axis.text = element_text(size = 16),
        title = element_text(size = 20),
        legend.text = element_text(size = 12)) +
  labs(x = "PC1 (28.1%)",
       y = "PC3 (11.5%)",
       title = "PC1 and PC3",
       color = "Scientific name") 
plot_PCA_13

pca_together <- (plot_PCA_12 | plot_PCA_13) +
  plot_layout(guides = "collect", ncol = 2, widths = c(1, 1)) &
  theme(legend.position = "bottom")
pca_together

# get loading contributions
loadings <- scores(tbs_pca, display = 'species', scaling = 0)
sort(abs(loadings[,1]), decreasing = TRUE)
sort(abs(loadings[,2]), decreasing = TRUE)

# ggsave(here::here("figures/prelim-ordinations",
#                   paste("PCA_together_cont-", today(), ".jpg", sep = "")),
#        pca_together,
#        width = 20, height = 8, dpi = 150)
# 
# ggsave(here::here("figures/prelim-ordinations",
#                   paste("PCA_spp-all-12-", today(), ".jpg", sep = "")),
#        plot_PCA_12,
#        width = 16, height = 8, dpi = 150)
# 
# ggsave(here::here("figures/prelim-ordinations",
#                   paste("PCA_spp-all-13-", today(), ".jpg", sep = "")),
#        plot_PCA_13,
#        width = 10, height = 10, dpi = 150)
```

# 3. Corrplot

```{r}
M <- pca_mat %>% 
  cor()

corr_traits <- corrplot(M, method = "circle", type = "lower", insig = "blank", addCoef.col = "black")

ggpairs(pca_mat)

corr_traits

var <- get_pca_var(tbs_pca)
corrplot(var$contrib, is.corr=FALSE)  
```

# 4. PTCA adults vs recruits

```{r}
tbsample_matrix_ptca <- av_leaf_values %>% 
  left_join(., metadata_ind, by = "specimen_ID") %>% 
  filter(sp_code == "PTCA") %>% 
  filter(site %in% c("Arroyo Quemado", "Mohawk")) %>% 
  left_join(., volume_ind, by = "specimen_ID") %>% 
  left_join(., fvfm_ind, by = "specimen_ID") %>% 
  left_join(., ind_height, by = "specimen_ID") %>% 
  dplyr::select(site, lifestage, specimen_ID, sta_mean, tdmc_mean, total_volume, fvfm_mean, frond_length_mean, frond_width_mean, maximum_height) %>% 
  rename("FvFm" = fvfm_mean,
         "STA" = sta_mean,
         "TDMC" = tdmc_mean,
         "Volume" = total_volume,
         "Frond length" = frond_length_mean,
         "Frond width" = frond_width_mean,
         "Maximum height" = maximum_height)

tbsample_mat <- av_leaf_values %>% 
  left_join(., metadata_ind, by = "specimen_ID") %>% 
  filter(sp_code == "PTCA") %>% 
  filter(site %in% c("Arroyo Quemado", "Mohawk")) %>% 
  left_join(., volume_ind, by = "specimen_ID") %>% 
  left_join(., fvfm_ind, by = "specimen_ID") %>% 
  left_join(., ind_height, by = "specimen_ID") %>% 
  dplyr::select(specimen_ID, sta_mean, tdmc_mean, total_volume, fvfm_mean, frond_length_mean, frond_width_mean, maximum_height) %>% 
  rename("FvFm" = fvfm_mean,
         "STA" = sta_mean,
         "TDMC" = tdmc_mean,
         "Volume" = total_volume,
         "Frond length" = frond_length_mean,
         "Frond width" = frond_width_mean,
         "Maximum height" = maximum_height) %>% 
  column_to_rownames("specimen_ID") %>% 
  drop_na()

tbsample_meta <- tbsample_matrix_ptca %>% 
  select(specimen_ID, lifestage, site) %>% 
  filter(specimen_ID %in% rownames(tbsample_mat))

ptca_pca <- rda(tbsample_mat, scale = TRUE)
summary(ptca_pca)
biplot(ptca_pca)

# species points
PCAscores_12_ptca <- scores(ptca_pca, display = "sites", choices = c(1, 2)) %>% 
  as.data.frame() %>% 
  rownames_to_column("specimen_ID") %>% 
  left_join(., tbsample_meta, by = "specimen_ID")

PCAscores_13_ptca <- scores(tbs_pca, display = "sites", choices = c(1, 3)) %>% 
  as.data.frame() %>% 
  rownames_to_column("specimen_ID") %>% 
  left_join(., tbsample_meta, by = "specimen_ID")

# trait vectors
PCAvect_12_ptca <- scores(ptca_pca, display = "species", choices = c(1, 2)) %>% 
  as.data.frame()

PCAvect_13_ptca <- scores(ptca_pca, display = "species", choices = c(1, 3)) %>% 
  as.data.frame()

# plot PCA
plot_PCA_12_ptca <- ggplot() +
  coord_cartesian() +
  geom_point(data = PCAscores_12_ptca, aes(x = PC1, y = PC2, color = lifestage, shape = site), size = 3, alpha = 0.9) +
  scale_color_manual(values = c("#70601d", "#b59b33")) +
  # geom_text(data = PCAscores, aes(x = PC1, y = PC2, color = scientific_name, label = specimen_ID)) +
  # scale_color_manual(values = pal) +
  geom_vline(xintercept = c(0), color = "grey70", linetype = 2) +
  geom_hline(yintercept = c(0), color = "grey70", linetype = 2) +
  geom_segment(data = PCAvect_12_ptca, aes(x = 0, y = 0, xend = PC1, yend = PC2), arrow = arrow(length = unit(0.2, "cm")), size = 1) +
  geom_text_repel(data = PCAvect_12_ptca, aes(x = PC1, y = PC2, label = rownames(PCAvect_12_ptca)), size = 6, alpha = 0.8) +
  # scale_x_continuous(limits = c(-1, 2.1)) +
  # scale_y_continuous(limits = c(-2.7, 1.6)) +
  theme_bw() +
  guides(colour = guide_legend(ncol = 2),
         shape = guide_legend(ncol = 2)) +
  theme(legend.position = "bottom", 
        legend.box = "vertical", 
        legend.margin = margin(),
        axis.title = element_text(size = 18),
        axis.text = element_text(size = 16),
        title = element_text(size = 20),
        legend.text = element_text(size = 12),
        legend.key = element_rect(size = 11), 
        panel.grid = element_blank()) +
  labs(x = "PC1 (59.07%)",
       y = "PC2 (19.14%)",
       color = "Life stage") 
plot_PCA_12_ptca

plot_PCA_13 <- ggplot() +
  coord_cartesian() +
  geom_point(data = PCAscores_13, aes(x = PC1, y = PC3, color = scientific_name, shape = site), size = 3, alpha = 0.8) +
  # geom_text(data = PCAscores, aes(x = PC1, y = PC2, color = scientific_name, label = specimen_ID)) +
  # scale_color_manual(values = pal) +
  geom_vline(xintercept = c(0), color = "grey70", linetype = 2) +
  geom_hline(yintercept = c(0), color = "grey70", linetype = 2) +
  geom_segment(data = PCAvect_13, aes(x = 0, y = 0, xend = PC1, yend = PC3), arrow = arrow(length = unit(0.2, "cm")), size = 1) +
  geom_text(data = PCAvect_13, aes(x = PC1, y = PC3, label = rownames(PCAvect)), size = 5, alpha = 0.8) +
  scale_x_continuous(limits = c(-1, 2.1)) +
  scale_y_continuous(limits = c(-2.7, 1.6)) +
  theme_bw() +
  guides(colour = guide_legend(ncol = 2),
         shape = guide_legend(ncol = 2)) +
  theme(legend.position = "bottom", 
        legend.box = "vertical", 
        legend.margin = margin(),
        axis.title = element_text(size = 18),
        axis.text = element_text(size = 16),
        title = element_text(size = 20),
        legend.text = element_text(size = 12)) +
  labs(x = "PC1 (42.4%)",
       y = "PC3 (12.4%)",
       title = "PC1 and PC3",
       color = "Scientific name") 
plot_PCA_13

pca_together <- (plot_PCA_12 | plot_PCA_13) +
  plot_layout(guides = "collect", ncol = 2, widths = c(1, 1)) &
  theme(legend.position = "bottom")
pca_together
```

# 5. environmental conditions

```{r}
env_mat <- CWM_fixed_filtered %>% 
  dplyr::select(transect_ID, mean_urchins, mean_subs, mean_kelp, mean_umol) %>% 
  column_to_rownames("transect_ID") %>% 
  drop_na()

corrplot(cor(env_mat), method = "circle", type = "lower", insig = "blank", addCoef.col = "black")


env_pca <- rda(env_mat, scale = TRUE)

summary(env_pca)
biplot(env_pca)

PCAscores_12_env <- scores(env_pca, display = "sites", choices = c(1, 2)) %>% 
  as.data.frame() %>% 
  rownames_to_column("transect_ID") %>% 
  left_join(., community_metadata_transect, by = "transect_ID")

PCAvect_12_env <- scores(env_pca, display = "species", choices = c(1, 2)) %>% 
  as.data.frame()

plot_PCA_12_env <- ggplot() +
  coord_cartesian() +
  geom_point(data = PCAscores_12_env, aes(x = PC1, y = PC2, color = site, shape = site), size = 3, alpha = 0.7) +
  # scale_color_manual(values = c("#70601d", "#b59b33")) +
  # geom_text(data = PCAscores, aes(x = PC1, y = PC2, color = scientific_name, label = specimen_ID)) +
  # scale_color_manual(values = pal) +
  geom_vline(xintercept = c(0), color = "grey70", linetype = 2) +
  geom_hline(yintercept = c(0), color = "grey70", linetype = 2) +
  geom_segment(data = PCAvect_12_env, aes(x = 0, y = 0, xend = PC1, yend = PC2), arrow = arrow(length = unit(0.2, "cm")), size = 1) +
  geom_text_repel(data = PCAvect_12_env, aes(x = PC1, y = PC2, label = rownames(PCAvect_12_env)), size = 6, alpha = 0.8) +
  # scale_x_continuous(limits = c(-1, 2.1)) +
  # scale_y_continuous(limits = c(-2.7, 1.6)) +
  theme_bw() +
  guides(colour = guide_legend(ncol = 1),
         shape = guide_legend(ncol = 1)) +
  theme(legend.position = c(0.9, 0.2),
        legend.box = "vertical", 
        legend.margin = margin(),
        axis.title = element_text(size = 18),
        axis.text = element_text(size = 16),
        title = element_text(size = 20),
        legend.text = element_text(size = 12),
        legend.key = element_rect(size = 11), 
        panel.grid = element_blank()) +
  labs(x = "PC1 (31.26%)",
       y = "PC2 (28.56%)") 
plot_PCA_12_env

adonis2(env_mat ~ site, data = CWM_fixed_filtered, method = "euclidean")
```

# 6. LTEs

```{r}

```

